import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
// import AuthProvider from "@/context/AuthProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <AuthProvider> */}
        <body className={`antialiased ${dmSans.className}`}>
          {children}
        </body>
      {/* </AuthProvider> */}
    </html>
  );
}
